spring:
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        # 连接池最大连接数(负表示没有限制)
        max-active: 100
        # 连接池对打阻塞等待时间（负表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲链接
        max-idle: 500
        # 连接池中的最小空闲链接
        min-idle: 0
    lettuce:
      # 链接超时时间
      shutdown-timeout: 0

# pageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql