server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: admin

mybatis:
  mapper-locations: classpath:mapperxml/*.xml
  type-aliases-package: cn.xmh.web.blogserver.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    aggressive-lazy-loading: false

#日志配置
logging:
  level:
    root: info
    cn.xmh.web: debug
  file:
    name: ./log/blog-dev.log
